## Next_Word_Prediction

In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import LSTM,Dense,Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
import pickle
import numpy as np
import os

In [3]:
file = open("book.txt","r",encoding="utf8")

In [4]:
lines = []
for i in file:
    lines.append(i)

In [5]:
lines

['\ufeffThe Project Gutenberg eBook of Pride and prejudice, by Jane Austen\n',
 '\n',
 'This eBook is for the use of anyone anywhere in the United States and\n',
 'most other parts of the world at no cost and with almost no restrictions\n',
 'whatsoever. You may copy it, give it away or re-use it under the terms\n',
 'of the Project Gutenberg License included with this eBook or online at\n',
 'www.gutenberg.org. If you are not located in the United States, you\n',
 'will have to check the laws of the country where you are located before\n',
 'using this eBook.\n',
 '\n',
 'Title: Pride and prejudice\n',
 '\n',
 'Author: Jane Austen\n',
 '\n',
 'Release Date: November 12, 2022 [eBook #1342]\n',
 '[Most recently updated: April 14, 2023]\n',
 '\n',
 'Language: English\n',
 '\n',
 'Produced by: Chuck Greif and the Online Distributed Proofreading Team at\n',
 '             http://www.pgdp.net (This file was produced from images\n',
 '             available at The Internet Archive)\n',
 '\n'

In [6]:
### i'm going to convert the list into string
data = ""
for i in lines:
    data = ' '.join(lines)

In [7]:
data

'\ufeffThe Project Gutenberg eBook of Pride and prejudice, by Jane Austen\n \n This eBook is for the use of anyone anywhere in the United States and\n most other parts of the world at no cost and with almost no restrictions\n whatsoever. You may copy it, give it away or re-use it under the terms\n of the Project Gutenberg License included with this eBook or online at\n www.gutenberg.org. If you are not located in the United States, you\n will have to check the laws of the country where you are located before\n using this eBook.\n \n Title: Pride and prejudice\n \n Author: Jane Austen\n \n Release Date: November 12, 2022 [eBook #1342]\n [Most recently updated: April 14, 2023]\n \n Language: English\n \n Produced by: Chuck Greif and the Online Distributed Proofreading Team at\n              http://www.pgdp.net (This file was produced from images\n              available at The Internet Archive)\n \n *** START OF THE PROJECT GUTENBERG EBOOK PRIDE AND PREJUDICE ***\n \n \n \n \n \n        

In [8]:
#### Replace unnecessory characters with space
data = data.replace('\n','').replace('\r','').replace('\ufeff','').replace('"','')

In [9]:
data

"The Project Gutenberg eBook of Pride and prejudice, by Jane Austen  This eBook is for the use of anyone anywhere in the United States and most other parts of the world at no cost and with almost no restrictions whatsoever. You may copy it, give it away or re-use it under the terms of the Project Gutenberg License included with this eBook or online at www.gutenberg.org. If you are not located in the United States, you will have to check the laws of the country where you are located before using this eBook.  Title: Pride and prejudice  Author: Jane Austen  Release Date: November 12, 2022 [eBook #1342] [Most recently updated: April 14, 2023]  Language: English  Produced by: Chuck Greif and the Online Distributed Proofreading Team at              http://www.pgdp.net (This file was produced from images              available at The Internet Archive)  *** START OF THE PROJECT GUTENBERG EBOOK PRIDE AND PREJUDICE ***                                  [Illustration:                             

In [10]:
#### Remove the unnecessory spaces by converting into a array and again into String
data = data.split()

In [11]:
data

['The',
 'Project',
 'Gutenberg',
 'eBook',
 'of',
 'Pride',
 'and',
 'prejudice,',
 'by',
 'Jane',
 'Austen',
 'This',
 'eBook',
 'is',
 'for',
 'the',
 'use',
 'of',
 'anyone',
 'anywhere',
 'in',
 'the',
 'United',
 'States',
 'and',
 'most',
 'other',
 'parts',
 'of',
 'the',
 'world',
 'at',
 'no',
 'cost',
 'and',
 'with',
 'almost',
 'no',
 'restrictions',
 'whatsoever.',
 'You',
 'may',
 'copy',
 'it,',
 'give',
 'it',
 'away',
 'or',
 're-use',
 'it',
 'under',
 'the',
 'terms',
 'of',
 'the',
 'Project',
 'Gutenberg',
 'License',
 'included',
 'with',
 'this',
 'eBook',
 'or',
 'online',
 'at',
 'www.gutenberg.org.',
 'If',
 'you',
 'are',
 'not',
 'located',
 'in',
 'the',
 'United',
 'States,',
 'you',
 'will',
 'have',
 'to',
 'check',
 'the',
 'laws',
 'of',
 'the',
 'country',
 'where',
 'you',
 'are',
 'located',
 'before',
 'using',
 'this',
 'eBook.',
 'Title:',
 'Pride',
 'and',
 'prejudice',
 'Author:',
 'Jane',
 'Austen',
 'Release',
 'Date:',
 'November',
 '12,',


In [12]:
data = ' '.join(data)

In [13]:
data[:500]

'The Project Gutenberg eBook of Pride and prejudice, by Jane Austen This eBook is for the use of anyone anywhere in the United States and most other parts of the world at no cost and with almost no restrictions whatsoever. You may copy it, give it away or re-use it under the terms of the Project Gutenberg License included with this eBook or online at www.gutenberg.org. If you are not located in the United States, you will have to check the laws of the country where you are located before using th'

In [14]:
len(data)

737635

In [15]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])

In [16]:
####for prediction function i'm going to save my tokenizer model
pickle.dump(tokenizer,open("my_tokenizer","wb"))

In [17]:
sequence_of_data = tokenizer.texts_to_sequences([data])[0]

In [18]:
sequence_of_data[:20]

[1,
 182,
 163,
 1030,
 3,
 305,
 4,
 975,
 30,
 73,
 726,
 42,
 1030,
 24,
 22,
 1,
 515,
 3,
 560,
 2716]

Now each word will get the unique number

In [19]:
len(sequence_of_data)

133014

In [20]:
vocab_size = len(tokenizer.word_index)+1
vocab_size

7548

#### i'm going to train my model by passing three words are input and predict next word. i select 4 words as one set in which 3 of them are input and 4 th one is output

In [21]:
sequences = []
for i in range(3,len(sequence_of_data)):
    words = sequence_of_data[i-3:i+1]
    print(words)
    break
    

[1, 182, 163, 1030]


In [22]:
sequences = []
for i in range(3,len(sequence_of_data)):
    words = sequence_of_data[i-3:i+1]
    sequences.append(words)
sequences[:10]

[[1, 182, 163, 1030],
 [182, 163, 1030, 3],
 [163, 1030, 3, 305],
 [1030, 3, 305, 4],
 [3, 305, 4, 975],
 [305, 4, 975, 30],
 [4, 975, 30, 73],
 [975, 30, 73, 726],
 [30, 73, 726, 42],
 [73, 726, 42, 1030]]

In [23]:
print('length of the sequences are',len(sequences))

length of the sequences are 133011


Now i'm going to convert my sequences array into X and Y for training my model

In [24]:
X = []
Y = []
for i in sequences:
    X.append(i[0:3])
    Y.append(i[3])
X = np.array(X)
Y = np.array(Y)
print("inputs :",X[:10])
print("responses :",Y[:10])

inputs : [[   1  182  163]
 [ 182  163 1030]
 [ 163 1030    3]
 [1030    3  305]
 [   3  305    4]
 [ 305    4  975]
 [   4  975   30]
 [ 975   30   73]
 [  30   73  726]
 [  73  726   42]]
responses : [1030    3  305    4  975   30   73  726   42 1030]


In [24]:
### Now i'm going to convert my target variable into onehotencoded vectors

In [25]:
y = to_categorical(Y,num_classes=vocab_size)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

The to_categorical function is commonly used to convert integer-encoded categorical variables into one-hot encoded vectors. It is often used in machine learning tasks, such as multi-class classification, where the target variable needs to be represented as a binary matrix.

### creating the model

In [26]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=3))
model.add(LSTM(1000, return_sequences=True))
model.add(LSTM(1000))
model.add(Dense(1000, activation="relu"))
model.add(Dense(vocab_size, activation="softmax"))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 10)             75480     
                                                                 
 lstm (LSTM)                 (None, 3, 1000)           4044000   
                                                                 
 lstm_1 (LSTM)               (None, 1000)              8004000   
                                                                 
 dense (Dense)               (None, 1000)              1001000   
                                                                 
 dense_1 (Dense)             (None, 7548)              7555548   
                                                                 
Total params: 20,680,028
Trainable params: 20,680,028
Non-trainable params: 0
_________________________________________________________________


model = Sequential()
model.add(Embedding(vocab_size,10,input_length=3))
model.add(LSTM(1000,return_sequences=True))
model.add(LSTM(1000))
model.add(Dense(1000,activation='relu'))
model.add(Dense(vocab_size,activation='softmax'))
model.summary()


#### train the model

In [27]:
from tensorflow.keras.callbacks import ModelCheckpoint
 
checkpoint = ModelCheckpoint("next_words.h5", monitor='loss', verbose=1, save_best_only=True)
model.compile(loss="categorical_crossentropy", optimizer=Adam(learning_rate=0.001))
model.fit(X, y, epochs=10, batch_size=64, callbacks=[checkpoint])

Epoch 1/10
2079/2079 [==============================] - ETA: 0s - loss: 6.2748
Epoch 1: loss improved from inf to 6.27483, saving model to next_words.h5
2079/2079 [==============================] - 1310s 628ms/step - loss: 6.2748
Epoch 2/10
2079/2079 [==============================] - ETA: 0s - loss: 5.6208
Epoch 2: loss improved from 6.27483 to 5.62084, saving model to next_words.h5
2079/2079 [==============================] - 682s 328ms/step - loss: 5.6208
Epoch 3/10
2079/2079 [==============================] - ETA: 0s - loss: 5.2606
Epoch 3: loss improved from 5.62084 to 5.26056, saving model to next_words.h5
2079/2079 [==============================] - 687s 330ms/step - loss: 5.2606
Epoch 4/10
2079/2079 [==============================] - ETA: 0s - loss: 5.0149
Epoch 4: loss improved from 5.26056 to 5.01490, saving model to next_words.h5
2079/2079 [==============================] - 721s 347ms/step - loss: 5.0149
Epoch 5/10
2079/2079 [==============================] - ETA: 0s - loss:

batch_size = 64 means that model will take first 64 samples to train the model, then takes next 64 and go on

In [29]:
import joblib
joblib.dump(model,"joblib_saved_model")

['joblib_saved_model']